export const bigFiveQuestions = [
  {statement: "Am the life of the party.", value: +1},
  {statement: "Feel little concern for others.", value: -2},
  {statement: "Am always prepared.", value: +3},
  {statement: "Get stressed out easily.", value: -4},
  {statement: "Have a rich vocabulary.", value: +5},
  {statement: "Don't talk a lot.", value: -1},
  {statement: "Am interested in people.", value: +2},
  {statement: "Leave my belongings around.", value: -3},
  {statement: "Am relaxed most of the time.", value: +4},
  {statement: "Have difficulty understanding abstract ideas.", value: -5},
  {statement: "Feel comfortable around people.", value: +1},
  {statement: "Insult people.", value: -2},
  {statement: "Pay attention to details.", value: +3},
  {statement: "Worry about things.", value: -4},
  {statement: "Have a vivid imagination.", value: +5},
  {statement: "Keep in the background.", value: -1},
  {statement: "Sympathize with others' feelings.", value: +2},
  {statement: "Make a mess of things.", value: -3},
  {statement: "Seldom feel blue.", value: +4},
  {statement: "Am not interested in abstract ideas.", value: -5},
  {statement: "Start conversations.", value: +1},
  {statement: "Am not interested in other people's problems.", value: -2},
  {statement: "Get chores done right away.", value: +3},
  {statement: "Am easily disturbed.", value: -4},
  {statement: "Have excellent ideas.", value: +5},
  {statement: "Have little to say.", value: -1},
  {statement: "Have a soft heart.", value: +2},
  {statement: "Often forget to put things back in their proper place.", value: -3},
  {statement: "Get upset easily.", value: -4},
  {statement: "Do not have a good imagination.", value: -5},
  {statement: "Talk to a lot of different people at parties.", value: +1},
  {statement: "Am not really interested in others.", value: -2},
  {statement: "Like order.", value: +3},
  {statement: "Change my mood a lot.", value: -4},
  {statement: "Am quick to understand things.", value: +5},
  {statement: "Don't like to draw attention to myself.", value: -1},
  {statement: "Take time out for others.", value: +2},
  {statement: "Shirk my duties.", value: -3},
  {statement: "Have frequent mood swings.", value: -4},
  {statement: "Use difficult words.", value: +5},
  {statement: "Don't mind being the center of attention.", value: +1},
  {statement: "Feel others' emotions.", value: +2},
  {statement: "Follow a schedule.", value: +3},
  {statement: "Get irritated easily.", value: -4},
  {statement: "Spend time reflecting on things.", value: +5},
  {statement: "Am quiet around strangers.", value: -1},
  {statement: "Make people feel at ease.", value: +2},
  {statement: "Am exacting in my work.", value: +3},
  {statement: "Often feel blue.", value: -4},
  {statement: "Am full of ideas.", value: +5}
];
